const login=document.getElementById('login'),dash=document.getElementById('dashboard'),form=document.getElementById('property-form');let properties=[],currentMedia=[];
const ids=['business-type','status','property-code','display-order','title-ja','title-zh-cn','title-zh-tw','description-ja','description-zh-cn','description-zh-tw','address-ja','address-public','area-name','railway-line','nearest-station','station-walk','schools','stations','rent','management-fee','deposit','key-money','sale-price','floor-plan','area-sqm','floor-info','building-age','structure','available-date','features'];
const keyMap={'business-type':'business_type','property-code':'property_code','display-order':'display_order','title-ja':'title_ja','title-zh-cn':'title_zh_cn','title-zh-tw':'title_zh_tw','description-ja':'description_ja','description-zh-cn':'description_zh_cn','description-zh-tw':'description_zh_tw','address-ja':'address_ja','address-public':'address_public','area-name':'area_name','railway-line':'railway_line','nearest-station':'nearest_station','station-walk':'station_walk_minutes','management-fee':'management_fee','key-money':'key_money','sale-price':'sale_price','floor-plan':'floor_plan','area-sqm':'area_sqm','floor-info':'floor_info','building-age':'building_age','available-date':'available_date'};
SB.auth.getSession().then(({data})=>setSession(data.session));SB.auth.onAuthStateChange((_e,s)=>setSession(s));
function setSession(s){login.classList.toggle('hidden',!!s);dash.classList.toggle('hidden',!s);if(s)loadProperties()}
document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();note('login-message','正在登录…');const {error}=await SB.auth.signInWithPassword({email:document.getElementById('login-email').value.trim(),password:document.getElementById('login-password').value});if(error)note('login-message',error.message,true)};
document.getElementById('logout').onclick=()=>SB.auth.signOut();
async function loadProperties(){const {data,error}=await SB.from('properties').select('*').order('updated_at',{ascending:false});if(error)return note('message','无法读取房源：'+error.message,true);properties=data||[];document.getElementById('property-list').innerHTML=properties.length?properties.map(p=>`<div class="admin-item" data-id="${p.id}"><b>${esc(p.title_zh_cn||p.title_ja)}</b><br><small>${p.business_type==='rent'?'租赁':'买卖'} · ${statusText(p.status)} · ${p.property_code||'无编号'}</small></div>`).join(''):'<div class="notice">目前没有房源，请点击“新建房源”。</div>';document.querySelectorAll('.admin-item').forEach(x=>x.onclick=()=>openProperty(x.dataset.id))}
function statusText(s){return({draft:'草稿',published:'公开',reserved:'商谈中',closed:'已下架'})[s]||s}
function openProperty(id){const p=properties.find(x=>x.id===id);if(!p)return;clearForm();document.getElementById('property-id').value=p.id;ids.forEach(id=>{const el=document.getElementById(id),key=keyMap[id]||id.replace(/-/g,'_');let v=p[key];if(['schools','stations','features'].includes(id))v=(v||[]).join(', ');el.value=v??''});document.getElementById('foreigner-allowed').checked=!!p.foreigner_allowed;document.getElementById('student-allowed').checked=!!p.student_allowed;document.getElementById('pet-allowed').checked=!!p.pet_allowed;document.getElementById('delete-property').classList.remove('hidden');loadMedia(p.id);window.scrollTo({top:0,behavior:'smooth'})}
function clearForm(){form.reset();document.getElementById('property-id').value='';document.getElementById('display-order').value='0';document.getElementById('delete-property').classList.add('hidden');document.getElementById('media-section').classList.add('hidden');currentMedia=[]}
document.getElementById('new-property').onclick=clearForm;document.getElementById('clear-form').onclick=clearForm;
form.onsubmit=async e=>{e.preventDefault();const id=document.getElementById('property-id').value;const payload={};ids.forEach(fid=>{const el=document.getElementById(fid),key=keyMap[fid]||fid.replace(/-/g,'_');let v=el.value.trim();if(['schools','stations','features'].includes(fid))v=v?v.split(/[,，]/).map(x=>x.trim()).filter(Boolean):[];if(['display-order','station-walk','rent','management-fee','sale-price'].includes(fid))v=v===''?null:Number(v);if(fid==='area-sqm')v=v===''?null:Number(v);payload[key]=v===''?null:v});payload.foreigner_allowed=document.getElementById('foreigner-allowed').checked;payload.student_allowed=document.getElementById('student-allowed').checked;payload.pet_allowed=document.getElementById('pet-allowed').checked;const old=id?properties.find(x=>x.id===id):null;if(payload.status==='published'&&!old?.published_at)payload.published_at=new Date().toISOString();note('message','正在保存…');let saved,error;if(id){({data:saved,error}=await SB.from('properties').update(payload).eq('id',id).select().single())}else{({data:saved,error}=await SB.from('properties').insert(payload).select().single())}if(error)return note('message','保存失败：'+error.message,true);const files=[...document.getElementById('media-files').files];if(files.length){const up=await uploadFiles(saved,files);if(up.error)return note('message','房源已保存，但文件上传失败：'+up.error,true)}note('message','房源已经保存。');document.getElementById('media-files').value='';await loadProperties();openProperty(saved.id)};
async function uploadFiles(p,files){for(let i=0;i<files.length;i++){const f=files[i],ext=(f.name.split('.').pop()||'bin').toLowerCase(),path=`${p.id}/${Date.now()}-${i}.${ext}`;const {error}=await SB.storage.from('property-media').upload(path,f,{contentType:f.type,upsert:false});if(error)return{error:error.message};const {data:url}=SB.storage.from('property-media').getPublicUrl(path);const type=f.type.startsWith('video/')?'video':'image';const {error:dbError}=await SB.from('property_media').insert({property_id:p.id,media_type:type,file_url:url.publicUrl,display_order:currentMedia.length+i});if(dbError)return{error:dbError.message};if(!p.cover_image_url&&type==='image'){await SB.from('properties').update({cover_image_url:url.publicUrl}).eq('id',p.id);p.cover_image_url=url.publicUrl}}return{}}
async function loadMedia(id){const {data}=await SB.from('property_media').select('*').eq('property_id',id).order('display_order');currentMedia=data||[];document.getElementById('media-section').classList.remove('hidden');document.getElementById('media-list').innerHTML=currentMedia.length?currentMedia.map(m=>`<div class="media-item">${m.media_type==='video'?`<video src="${m.file_url}" muted></video>`:`<img src="${m.file_url}" alt="">`}<button type="button" data-mid="${m.id}" data-url="${m.file_url}">×</button></div>`).join(''):'<div class="notice">尚未上传照片或视频。</div>';document.querySelectorAll('[data-mid]').forEach(b=>b.onclick=()=>deleteMedia(b.dataset.mid,b.dataset.url,id))}
async function deleteMedia(mid,url,pid){if(!confirm('确定删除这个文件吗？'))return;const marker='/property-media/';const path=decodeURIComponent(url.split(marker)[1]||'');if(path)await SB.storage.from('property-media').remove([path]);await SB.from('property_media').delete().eq('id',mid);const wasCover=properties.find(x=>x.id===pid)?.cover_image_url===url;if(wasCover){const next=currentMedia.find(x=>x.id!==mid&&x.media_type==='image');await SB.from('properties').update({cover_image_url:next?.file_url||null}).eq('id',pid)}await loadProperties();openProperty(pid)}
document.getElementById('delete-property').onclick=async()=>{const id=document.getElementById('property-id').value;if(!id||!confirm('确定彻底删除这套房源及全部文件吗？'))return;const prefix=`${id}/`;const {data:files}=await SB.storage.from('property-media').list(id,{limit:1000});if(files?.length)await SB.storage.from('property-media').remove(files.map(f=>prefix+f.name));const {error}=await SB.from('properties').delete().eq('id',id);if(error)return note('message',error.message,true);clearForm();note('message','房源已删除。');loadProperties()};
function note(id,msg,error=false){document.getElementById(id).innerHTML=`<div class="notice ${error?'error':''}">${esc(msg)}</div>`}function esc(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
