const requestedType=qp.get('type');const type=['rent','short','sale'].includes(requestedType)?requestedType:'rent';let records=[];
document.documentElement.lang=lang==='ja'?'ja':lang==='zh-tw'?'zh-Hant':'zh-Hans';
document.getElementById('header').innerHTML=header(type);document.getElementById('footer').innerHTML=footer();
document.getElementById('page-title').textContent=type==='rent'?t.rent:type==='short'?t.short:t.sale;
document.getElementById('page-lead').textContent=lang==='ja'?'京都の公開物件を、学校・駅・価格から検索できます。':lang==='zh-tw'?'可依學校、車站和價格搜尋京都公開物件。':'可按学校、车站和价格搜索京都公开房源。';
[['keyword-label','keyword'],['school-label','school'],['station-label','station'],['max-label','max'],['search-button','search'],['results-title','available'],['loading','loading']].forEach(([id,k])=>document.getElementById(id).textContent=t[k]);
async function load(){const {data,error}=await SB.from('properties').select('*').eq('business_type',type).eq('status','published').order('display_order',{ascending:false}).order('published_at',{ascending:false});if(error){showError(error.message);return}records=data||[];buildOptions();render()}
function buildOptions(){const schools=[...new Set(records.flatMap(x=>x.schools||[]).filter(Boolean))].sort();const stations=[...new Set(records.flatMap(x=>[x.nearest_station,...(x.stations||[])].filter(Boolean)))].sort();fill('school',schools,t.all);fill('station',stations,t.all)}
function fill(id,items,first){const el=document.getElementById(id);el.innerHTML=`<option value="">${first}</option>`+items.map(x=>`<option>${escapeHtml(x)}</option>`).join('')}
function render(){const q=document.getElementById('keyword').value.trim().toLowerCase(),school=document.getElementById('school').value,station=document.getElementById('station').value,max=Number(document.getElementById('max-price').value)||Infinity;const filtered=records.filter(p=>{const hay=[titleOf(p),p.address_public,p.area_name,p.city,p.nearest_station].join(' ').toLowerCase();const price=type==='sale'?p.sale_price:p.rent;return(!q||hay.includes(q))&&(!school||(p.schools||[]).includes(school))&&(!station||p.nearest_station===station||(p.stations||[]).includes(station))&&(!price||price<=max)});document.getElementById('results-count').textContent=filtered.length+' '+(lang==='ja'?'件':lang==='zh-tw'?'筆':'套');document.getElementById('property-grid').innerHTML=filtered.length?filtered.map(card).join(''):`<div class="empty-state">${t.empty}</div>`}
function card(p){const price=type==='sale'?money(p.sale_price):`${money(p.rent)}${t.month}`;const cls=p.cover_image_url?'card-media':'card-media no-image';const typeLabel=type==='rent'?t.rent:type==='short'?t.short:t.sale;return `<a class="property-card" href="property.html?id=${p.id}&lang=${lang}" style="text-decoration:none"><div class="${cls}" ${p.cover_image_url?`style="background-image:url('${encodeURI(p.cover_image_url)}')"`:''}><span class="badge">${typeLabel}</span></div><div class="card-body"><h3>${escapeHtml(titleOf(p))}</h3><div class="price">${price}</div><div class="meta">${p.floor_plan?`<span>${escapeHtml(p.floor_plan)}</span>`:''}${p.area_sqm?`<span>${p.area_sqm}㎡</span>`:''}${p.foreigner_allowed?`<span>${t.foreign}</span>`:''}</div><div class="station">${escapeHtml(p.railway_line||'')} ${escapeHtml(p.nearest_station||'')}${p.station_walk_minutes?` ${t.walk}${p.station_walk_minutes}${t.min}`:''}</div></div></a>`}
function escapeHtml(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showError(m){document.getElementById('property-grid').innerHTML=`<div class="empty-state">${escapeHtml(m)}</div>`}
document.getElementById('search-button').addEventListener('click',render);['keyword','school','station','max-price'].forEach(id=>document.getElementById(id).addEventListener(id==='keyword'?'input':'change',render));load();
