const SB=window.supabase.createClient(window.ZUIHOUDOU_SUPABASE_URL,window.ZUIHOUDOU_SUPABASE_KEY);
const qp=new URLSearchParams(location.search);
const lang=qp.get('lang')||'zh-cn';
const copy={
  'zh-cn':{home:'公司首页',rent:'租赁房源',short:'短租房',sale:'买卖房源',all:'全部',school:'学校',station:'车站',keyword:'物件名称・区域',max:'最高价格',search:'搜索房源',available:'公开房源',loading:'正在读取房源…',empty:'目前没有符合条件的公开房源',month:'/月',walk:'步行',min:'分钟',area:'面积',layout:'户型',fee:'管理费',deposit:'敷金',keyMoney:'礼金',contact:'咨询这套房源',contactTitle:'请选择咨询方式',contactForm:'填写咨询表格',call:'拨打电话',email:'复制邮箱地址',emailCopied:'邮箱已复制',back:'返回房源一览',description:'房源介绍',address:'所在地',foreign:'外国籍可咨询',student:'学生可咨询',login:'管理员登录'},
  'zh-tw':{home:'公司首頁',rent:'租賃物件',short:'短租物件',sale:'買賣物件',all:'全部',school:'學校',station:'車站',keyword:'物件名稱・區域',max:'最高價格',search:'搜尋物件',available:'公開物件',loading:'正在讀取物件…',empty:'目前沒有符合條件的公開物件',month:'/月',walk:'步行',min:'分鐘',area:'面積',layout:'格局',fee:'管理費',deposit:'押金',keyMoney:'禮金',contact:'諮詢此物件',contactTitle:'請選擇諮詢方式',contactForm:'填寫諮詢表格',call:'撥打電話',email:'複製電郵地址',emailCopied:'電郵地址已複製',back:'返回物件一覽',description:'物件介紹',address:'所在地',foreign:'外國籍可諮詢',student:'學生可諮詢',login:'管理員登入'},
  ja:{home:'会社ホーム',rent:'賃貸物件',short:'短期賃貸',sale:'売買物件',all:'すべて',school:'学校',station:'駅',keyword:'物件名・エリア',max:'上限価格',search:'物件を検索',available:'公開中の物件',loading:'物件を読み込んでいます…',empty:'条件に合う公開物件はありません',month:'/月',walk:'徒歩',min:'分',area:'面積',layout:'間取り',fee:'管理費',deposit:'敷金',keyMoney:'礼金',contact:'この物件を問い合わせる',contactTitle:'お問い合わせ方法を選択',contactForm:'フォームで問い合わせる',call:'電話をかける',email:'メールアドレスをコピー',emailCopied:'メールアドレスをコピーしました',back:'物件一覧へ戻る',description:'物件紹介',address:'所在地',foreign:'外国籍相談可',student:'学生相談可',login:'管理者ログイン'}
};
const t=copy[lang]||copy['zh-cn'];
const titleOf=p=>lang==='ja'?p.title_ja:(lang==='zh-tw'?(p.title_zh_tw||p.title_zh_cn||p.title_ja):(p.title_zh_cn||p.title_ja));
const descOf=p=>lang==='ja'?p.description_ja:(lang==='zh-tw'?(p.description_zh_tw||p.description_zh_cn||p.description_ja):(p.description_zh_cn||p.description_ja));
const money=n=>n==null||n===''?'—':new Intl.NumberFormat(lang==='ja'?'ja-JP':'zh-CN').format(n)+'円';
const homeFor=()=>lang==='ja'?'jp.html':lang==='zh-tw'?'tw.html':'index.html';
function header(active){return `<header class="property-header"><div class="property-shell property-nav"><a class="property-brand" href="${homeFor()}"><span class="property-brand-mark">瑞鳳</span><span>瑞鳳堂株式会社</span></a><div class="property-links"><a class="home-label" href="${homeFor()}">${t.home}</a><a class="${active==='rent'?'active':''}" href="properties.html?type=rent&lang=${lang}">${t.rent}</a><a class="${active==='short'?'active':''}" href="properties.html?type=short&lang=${lang}">${t.short}</a><a class="${active==='sale'?'active':''}" href="properties.html?type=sale&lang=${lang}">${t.sale}</a></div><div class="lang-switch"><a class="${lang==='zh-cn'?'active':''}" href="${samePage('zh-cn')}">简</a><a class="${lang==='zh-tw'?'active':''}" href="${samePage('zh-tw')}">繁</a><a class="${lang==='ja'?'active':''}" href="${samePage('ja')}">日</a></div></div></header>`}
function samePage(next){const p=new URLSearchParams(location.search);p.set('lang',next);return location.pathname.split('/').pop()+'?'+p.toString()}
function footer(){return `<footer class="property-footer"><div class="property-shell">瑞鳳堂株式会社　｜　宅地建物取引業免許 京都府知事（1）第15170号　｜　<a href="mailto:info@zuihoudou.com">info@zuihoudou.com</a></div></footer>`}
